"""make lead email optional and add phone column

Revision ID: 792d01e92242
Revises: b33147b1af14
Create Date: 2026-08-20 09:58:26.738034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792d01e92242'
down_revision = 'b33147b1af14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
