"""add qr landing toggles

Revision ID: b33147b1af14
Revises: ac309500b1c7
Create Date: 2026-08-20 09:51:38.083937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33147b1af14'
down_revision = 'ac309500b1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_lead_form', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('show_call_button', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('call_phone_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.drop_column('call_phone_number')
        batch_op.drop_column('show_call_button')
        batch_op.drop_column('show_lead_form')

    # ### end Alembic commands ###
